// Generated by https://quicktype.io

import {OrderElement} from './loginInterface';

export interface Client {
  _id: string;
  name: string;
  surname: string;
  email: string;
  password: string;
  avatar: string;
  isDev: boolean;
  social: Social;
  info: Info;
  __v: number;
  orders: OrderElement[];
}

export interface Info {
  organization: string;
  time_zone: string;
  language: string[];
  _id: string;
}

export interface Social {
  linkedin: string;
  portfolio: string;
  github: string;
  _id: string;
}
